import { useEffect, useMemo, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import type { RootStackParamList } from '../../../navigation/types';
import type { ColorPalette } from '../../../theme/colors';
import { useAppPreferences } from '../../../theme/AppPreferencesProvider';
import { finalizeProjectMembers, listProjectMembersWithProfiles, type ProjectMemberWithProfile } from '../../applications/services/applicationService';
import { createPendingExperiences } from '../../experience/services/experienceService';
import { getProjectDetail, setProjectStatus } from '../services/projectService';

type Props=NativeStackScreenProps<RootStackParamList,'CompleteProject'>;
export default function CompleteProjectScreen({navigation,route}:Props){const{colors}=useAppPreferences();const insets=useSafeAreaInsets();const styles=useMemo(()=>makeStyles(colors,insets.top,insets.bottom),[colors,insets.bottom,insets.top]);const[members,setMembers]=useState<ProjectMemberWithProfile[]>([]);const[selected,setSelected]=useState<string[]>([]);const[title,setTitle]=useState('Progetto');
 useEffect(()=>{void Promise.all([listProjectMembersWithProfiles(route.params.projectId),getProjectDetail(route.params.projectId)]).then(([items,detail])=>{const active=items.filter((item)=>item.status==='active');setMembers(active);setSelected(active.map((item)=>item.userId));setTitle(detail?.project.title??'Progetto')})},[route.params.projectId]);
 const toggle=(id:string)=>setSelected((current)=>current.includes(id)?current.filter((item)=>item!==id):[...current,id]);
 const complete=()=>{if(selected.length===0){Alert.alert('Nessun partecipante selezionato','Seleziona almeno una persona che ha completato realmente il progetto.');return}Alert.alert('Confermare il completamento?',`${selected.length} partecipanti riceveranno un’esperienza in attesa della loro conferma.`,[{text:'Annulla',style:'cancel'},{text:'Conferma',onPress:async()=>{try{const detail=await getProjectDetail(route.params.projectId);if(!detail||detail.project.status!=='active')throw new Error('Il progetto non è in corso.');const completed=await finalizeProjectMembers(detail.project.id,selected);const project=await setProjectStatus(detail.project.id,'completed');await createPendingExperiences(project,completed);Alert.alert('Progetto completato','Le esperienze sono state create e dovranno essere confermate dai partecipanti.',[{text:'OK',onPress:()=>navigation.popTo('ProjectDetail',{projectId:project.id})}]);}catch(e){Alert.alert('Operazione non riuscita',e instanceof Error?e.message:'Errore imprevisto.')}}}])};
 return <View style={styles.container}><View style={styles.header}><TouchableOpacity style={styles.back} onPress={()=>navigation.goBack()}><Ionicons name="chevron-back" size={24} color={colors.textStrong}/></TouchableOpacity><View style={styles.headerCopy}><Text style={styles.headerTitle}>Completa progetto</Text><Text style={styles.headerSub}>{title}</Text></View><View style={styles.spacer}/></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Chi ha completato realmente il progetto?</Text><Text style={styles.subtitle}>Solo i partecipanti selezionati riceveranno una Crevia Experience da confermare. Gli altri membri attivi verranno chiusi senza esperienza verificata.</Text>{members.length===0?<View style={styles.empty}><Text style={styles.emptyText}>Non ci sono membri attivi da confermare.</Text></View>:members.map((member)=>{const checked=selected.includes(member.userId);return <TouchableOpacity key={member.id} style={[styles.card,checked&&styles.cardSelected]} onPress={()=>toggle(member.userId)}><View style={[styles.check,checked&&styles.checkActive]}>{checked?<Ionicons name="checkmark" size={18} color={colors.white}/>:null}</View><View style={styles.flex}><Text style={styles.name}>{member.profile.firstName} {member.profile.lastName}</Text><Text style={styles.role}>{member.roleTitle}</Text></View></TouchableOpacity>})}<TouchableOpacity disabled={members.length===0} style={[styles.button,members.length===0&&styles.buttonDisabled]} onPress={complete}><Text style={styles.buttonText}>Completa progetto</Text></TouchableOpacity></ScrollView></View>}
const makeStyles=(c:ColorPalette,top:number,bottom:number)=>StyleSheet.create({container:{flex:1,backgroundColor:c.background},header:{paddingTop:Math.max(top,24)+8,paddingHorizontal:16,paddingBottom:12,flexDirection:'row',alignItems:'center',backgroundColor:c.cardBackground,borderBottomWidth:1,borderBottomColor:c.border},back:{width:42,height:42,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:c.actionSurface},spacer:{width:42},headerCopy:{flex:1,alignItems:'center'},headerTitle:{fontSize:16,fontWeight:'900',color:c.textStrong},headerSub:{fontSize:11,color:c.gray},content:{padding:20,gap:14,paddingBottom:30+bottom},title:{fontSize:21,lineHeight:27,fontWeight:'900',color:c.textStrong},subtitle:{fontSize:13,lineHeight:20,color:c.textMuted},card:{flexDirection:'row',alignItems:'center',gap:12,padding:16,borderRadius:14,borderWidth:1,borderColor:c.border,backgroundColor:c.cardBackground},cardSelected:{borderColor:c.primary,backgroundColor:c.primarySoft},check:{width:26,height:26,borderRadius:8,borderWidth:1,borderColor:c.border,alignItems:'center',justifyContent:'center'},checkActive:{backgroundColor:c.primary,borderColor:c.primary},flex:{flex:1},name:{fontSize:15,fontWeight:'900',color:c.textStrong},role:{fontSize:12,fontWeight:'700',color:c.primary,marginTop:2},empty:{padding:20,borderRadius:14,backgroundColor:c.cardBackground,borderWidth:1,borderColor:c.border},emptyText:{textAlign:'center',color:c.textMuted},button:{marginTop:6,paddingVertical:15,borderRadius:12,alignItems:'center',backgroundColor:c.primary},buttonDisabled:{opacity:.4},buttonText:{color:c.white,fontSize:15,fontWeight:'900'}});
