import { useCallback, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from '@react-navigation/native';
import type { CompositeScreenProps } from '@react-navigation/native';
import type { MaterialTopTabScreenProps } from '@react-navigation/material-top-tabs';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import type { MainTabParamList, RootStackParamList } from '../../../navigation/types';
import type { Project, ProjectRole } from '../../../domain/models';
import type { ColorPalette } from '../../../theme/colors';
import { useAppPreferences } from '../../../theme/AppPreferencesProvider';
import { getProjectDetail, getProjectStatusLabel, listProjects } from '../services/projectService';

type Props=CompositeScreenProps<MaterialTopTabScreenProps<MainTabParamList,'Search'>,NativeStackScreenProps<RootStackParamList>>;
type Result={project:Project;roles:ProjectRole[]};
export default function SearchScreen({navigation}:Props){const {colors}=useAppPreferences();const insets=useSafeAreaInsets();const styles=useMemo(()=>makeStyles(colors,insets.top,insets.bottom),[colors,insets.bottom,insets.top]);const[query,setQuery]=useState('');const[items,setItems]=useState<Result[]>([]);
  const load=useCallback(async()=>{const projects=await listProjects();const results=await Promise.all(projects.map(async(project)=>({project,roles:(await getProjectDetail(project.id))?.roles??[]})));setItems(results);},[]);useFocusEffect(useCallback(()=>{void load();},[load]));
  const q=query.trim().toLowerCase();const filtered=items.filter(({project,roles})=>!q||[project.title,project.description,project.category,project.city??'',...roles.flatMap((r)=>[r.title,...r.requiredSkills])].some((value)=>value.toLowerCase().includes(q)));
  return <View style={styles.container}><View style={styles.header}><Text style={styles.logo}>CREVIA</Text><Text style={styles.headerTitle}>Cerca progetti</Text></View><View style={styles.searchBox}><Ionicons name="search" size={20} color={colors.gray}/><TextInput value={query} onChangeText={setQuery} placeholder="Progetto, ruolo, competenza, città..." placeholderTextColor={colors.gray} style={styles.input}/>{query?<TouchableOpacity onPress={()=>setQuery('')}><Ionicons name="close-circle" size={20} color={colors.gray}/></TouchableOpacity>:null}</View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.count}>{filtered.length} {filtered.length===1?'progetto':'progetti'}</Text>{filtered.map(({project,roles})=><TouchableOpacity key={project.id} style={styles.card} activeOpacity={0.78} onPress={()=>navigation.navigate('ProjectDetail',{projectId:project.id})}><View style={styles.cardTop}><View style={styles.icon}><Ionicons name="briefcase-outline" size={20} color={colors.primary}/></View><View style={styles.flex}><Text style={styles.title}>{project.title}</Text><Text style={styles.meta}>{project.category} · {project.city??'Remoto'} · {getProjectStatusLabel(project.status)}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.gray}/></View><Text numberOfLines={2} style={styles.description}>{project.description}</Text><View style={styles.chips}>{roles.slice(0,3).map((role)=><View key={role.id} style={styles.chip}><Text style={styles.chipText}>{role.title}</Text></View>)}</View></TouchableOpacity>)}{filtered.length===0?<View style={styles.empty}><Ionicons name="search-outline" size={30} color={colors.gray}/><Text style={styles.emptyTitle}>Nessun risultato</Text><Text style={styles.emptyText}>Prova con un ruolo, una competenza o una categoria diversa.</Text></View>:null}</ScrollView></View>}
const makeStyles=(c:ColorPalette,top:number,bottom:number)=>StyleSheet.create({container:{flex:1,backgroundColor:c.background},header:{paddingTop:Math.max(top,24)+14,paddingHorizontal:20,paddingBottom:13,backgroundColor:c.cardBackground},logo:{fontSize:24,fontWeight:'bold',color:c.primary,letterSpacing:1},headerTitle:{fontSize:13,color:c.gray,fontWeight:'700'},searchBox:{margin:20,marginBottom:4,flexDirection:'row',alignItems:'center',gap:9,paddingHorizontal:14,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.cardBackground},input:{flex:1,paddingVertical:13,color:c.textStrong,fontSize:14},content:{padding:20,gap:12,paddingBottom:90+bottom},count:{fontSize:12,fontWeight:'700',color:c.gray},card:{padding:16,gap:11,borderRadius:16,borderWidth:1,borderColor:c.border,backgroundColor:c.cardBackground},cardTop:{flexDirection:'row',alignItems:'center',gap:10},icon:{width:42,height:42,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:c.primarySoft},flex:{flex:1},title:{fontSize:16,fontWeight:'900',color:c.textStrong},meta:{fontSize:11,color:c.primary,fontWeight:'700',marginTop:2},description:{fontSize:13,lineHeight:19,color:c.textMuted},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:9,paddingVertical:6,borderRadius:8,backgroundColor:c.actionSurface},chipText:{fontSize:11,fontWeight:'700',color:c.textMuted},empty:{minHeight:220,alignItems:'center',justifyContent:'center',gap:8},emptyTitle:{fontSize:16,fontWeight:'900',color:c.textStrong},emptyText:{fontSize:12,color:c.textMuted,textAlign:'center'}});
